### PR TITLE
Upstreaming3

### PR DESCRIPTION
**Pull request by rpavlik**
A couple of fixes here, some are particularly important if you're using jnipp in a library (like the OpenXR loader) and thus don't have 100% control over when the thread gets attached/detached.

### CODE REVIEW

**Comment by rblenkinsopp** [comment]
@mitchdowd Is it possible to get these changes merged as I'm currently using them as well?

**Comment by rpavlik** [comment]
I was added to this repo as a committer, but didn't get any guidelines as to when to merge things. I can't review my own code, but if these changes also work for you that seems like a good test.

**Comment by rblenkinsopp** [comment]
I've certainly been using this branch for our usage, though I won't be hitting all of the fixes you've listed here. I was primarily this version for the fixes around the manual thread attach.

**Comment by mitchdowd** [comment]
Merged.  Thanks for the contribution @rpavlik .  I'm happy for you to self-approve and merge at this point.

**Pull request merged**
